### ISSUE TITLE
In reactjs viks_cart folder is not opening...

### ISSUE THREAD

**Issue by harinadh76** [KrazyDevelopers/hacktober-2022#15]
May the folder is not pushed properly....

**Comment by KartikeSingh** [comment]
It's a sub module, so kind of like linking another repository inside this one!
maybe I will create a `.gitmodules` file

**Comment by KartikeSingh** [comment]
thank makes sense too, lemme check what I can do.

**Comment by harinadh76** [comment]
yeah.. same thing happened to me last time .. deleted .git and pushed it again..

**Comment by KartikeSingh** [comment]
Fixed that in this [commit](https://github.com/KrazyDevelopers/hacktober-2022/commit/e2dae657b69bb9daf1d7a04a4c12b2689cad7898).

**Comment by harinadh76** [comment]
Nice : )
