### ISSUE TITLE
To Add Tic-Tac-Toe game made in Python

### ISSUE THREAD

**Issue by SukarayamJanjua** [KrazyDevelopers/hacktober-2022#18]
Hey there, I want to add a tic-tac-toe game which is made in python its not a GUI based game but it has complete algorithm required to play it on terminal both for single player and multiplayer !!

**Comment by SukarayamJanjua** [comment]
Kindly add hactoberfest label to it...the project is ready I'll upload it in one go 😊

**Comment by KartikeSingh** [comment]
Closing the issue because PR is merged
